<a href="https://colab.research.google.com/github/xiomiliseth02-beep/Estad-stica-I/blob/main/bono_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Bono: manejo de Numpy y Pandas

###Xiomara Liseth Muñoz Villamizar - 2240139

#Numpy:
Su función principal es facilitar el trabajo con datos numéricos de manera rápida, ordenada y eficiente. Un objeto de tipo numpy es un arreglo fundamental para realizar operaciones matemáticas y manipulación de datos en Python.

#Pandas:
Se emplea para manejar datos estructurados, similares a los de hojas de cálculo o bases de datos. Un objeto de tipo pandas permite cargar, limpiar, transformar y analizar información. Lo utilizamos especialmente para trabajar con bases de datos relacionales.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#1. NUMPY

##1.1 ¿Cómo crear arreglos simples con código Numpy?

Arreglo matricial en donde todos los elementos son "0":

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Arreglo matricial en donde todos los elementos son "1":

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Arreglo de una matriz identidad de tamaño cuadrado:

In [ ]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

El código presentado recibe tres valores de entrada (a, b, c) y genera un arreglo que comienza en a, llega hasta b (sin incluir este valor), y avanza de c en c entre cada elemento del arreglo.

In [ ]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

Si queremos un arreglo con elementos igualmente espaciados dentro de un intervalo fijo, usamos (a, b, c), donde a y b son el inicio y el final del intervalo, y c es la cantidad de elementos que queremos.

In [ ]:
np.linspace(0, 15, 7 )

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. ])

In [ ]:
np.random.rand(10)

array([0.57909182, 0.06066949, 0.76492981, 0.83811041, 0.95679929,
       0.87314143, 0.45957289, 0.51071227, 0.04352414, 0.73767848])

In [ ]:
np.random.randint(0, 10)

8

In [ ]:
np.random.randn(8)

array([ 0.0088418 ,  0.64965509, -1.21560179,  1.26559921,  0.55415861,
       -1.84222682,  0.31775982, -0.65562631])

##1.2 Propiedades para el análisis de arreglos usando Numpys:

Contruyendo una lista (lista), dos arreglos matriciales (arrM1) y (arrM2) y un arreglo vectorial (arrV):

In [ ]:
lista = [20,5,4]
arrM1 = np.array([[5,11, 9],
                  [0, 7, 5],
                  [13, -3, 8]])
arrM2 = np.array([[1,-4, 6],
                  [5, 2, -3],
                   [8, 1, 4]])
arrV = np.array([11,24,33,30, 23, 24, 37, 27, 25])

Queremos crear una nueva lista que tenga tantas copias como elementos tiene la lista original, pero repitiendo dos veces cada componente de la lista original.

In [ ]:
lista * 2

[20, 5, 4, 20, 5, 4]

Si queremos multiplicar todos los elementos de un arreglo por un mismo valor, podemos usar cualquiera de estas opciones:

In [ ]:
arrM1 * 2

array([[10, 22, 18],
       [ 0, 14, 10],
       [26, -6, 16]])

In [ ]:
[x*3 for x in arrM2]

[array([  3, -12,  18]), array([15,  6, -9]), array([24,  3, 12])]

Si queremos saber cuántas dimensiones tiene nuestro arreglo y cuántos elementos hay en cada una de ellas:

In [ ]:
arrM2.shape

(3, 3)

Si queremos saber la dimension de nuestro arreglo:

In [ ]:
arrM1.ndim

2

Si queremos saber el tipo de componentes que tenemos en nuestro arreglo:

In [ ]:
arrV.dtype

dtype('int64')

Si queremos saber la cantidad de elementos que tenemos en todo el arreglo:

In [ ]:
arrM1.size

9

Para saber la primera componenete del arreglo:

In [ ]:
arrM2[0]

array([ 1, -4,  6])

Para saber la ultima componente del arreglo:

In [ ]:
arrM1[-1]

array([13, -3,  8])

Para conocer todas las componentes en el intervalo sin tomar la componente de la pocision del final del intervalo:

In [ ]:
arrM1[0:2]

array([[ 5, 11,  9],
       [ 0,  7,  5]])

En el siguiente código deducimos que las entradas:

- $[a, b]$ da el elemento en esas coordenadas,
- $[:, b]$ da todos los elementos que estén en la posición $b$ en cada arreglo,
- $[a, :]$ da la componente $a$ del arreglo.

Teniendo en cuenta que las posiciones empiezan desde el $0$.

In [ ]:
print(arrM2[0,2], arrM2[:,2], arrM2[2,:])

6 [ 6 -3  4] [8 1 4]

In [ ]:
arrM1 + arrM2

array([[ 6,  7, 15],
       [ 5,  9,  2],
       [21, -2, 12]])

In [ ]:
arrM1 * arrM2

array([[  5, -44,  54],
       [  0,  14, -15],
       [104,  -3,  32]])

In [ ]:
np.dot(arrM1,arrM2)

array([[132,  11,  33],
       [ 75,  19,  -1],
       [ 62, -50, 119]])

Calcula media, mediana, desviacion estandar, suma de todos los valores, elmento minimo y maximo:

In [ ]:
print( np.mean(arrV), np.median(arrV), np.std(arrV), np.sum(arrV), np.min(arrV), np.max(arrV))

26.0 25.0 6.912147117775907 234 11 37

##1.3 Manipulación de arreglos:

Convertir un arreglo tipo vector en una matriz:

In [ ]:
arrV.reshape(3,3)

array([[11, 24, 33],
       [30, 23, 24],
       [37, 27, 25]])

Unir arreglos:

In [ ]:
np.concatenate([arrM1, arrM2])

array([[ 5, 11,  9],
       [ 0,  7,  5],
       [13, -3,  8],
       [ 1, -4,  6],
       [ 5,  2, -3],
       [ 8,  1,  4]])

Convertir un arreglo matricial en un tipo vector:

In [ ]:
np.concatenate(arrM2.reshape(3,3))

array([ 1, -4,  6,  5,  2, -3,  8,  1,  4])

In [ ]:
arrM2.flatten()

array([ 1, -4,  6,  5,  2, -3,  8,  1,  4])

Calcular la inversa de la matriz de un arreglo:

In [ ]:
np.linalg.inv(arrM1)

array([[ 0.28286853, -0.45816733, -0.03187251],
       [ 0.25896414, -0.30677291, -0.09960159],
       [-0.3625498 ,  0.62948207,  0.13944223]])

Calcular la transpuesta de la matriz de un arreglo:

In [ ]:
np.linalg.matrix_transpose(arrM2)

array([[ 1,  5,  8],
       [-4,  2,  1],
       [ 6, -3,  4]])

##1.4 Filtrado y condición

Encontrar valores que cumplan una condicion:

In [ ]:
arrV[arrV>20]

array([24, 33, 30, 23, 24, 37, 27, 25])

In [ ]:
arrV[(arrV>20) & (arrV < 30)]

array([24, 23, 24, 27, 25])

Encuentra los valores dado la condicion y los remplaza segun queramos

In [ ]:
# para este caso los valores que cumplan la condicion se remplazan con 1 y los queno con 0
np.where(arrV>30, 1, 0)

array([0, 0, 1, 0, 0, 0, 1, 0, 0])

In [ ]:
np.where(arrV>25, 0, arrV)

array([11, 24,  0,  0, 23, 24,  0,  0, 25])

#2. Pandas

##2.1 Analisis de tablas a travez de pandas:

Construimos una tabla:
al crear un DataFrame.
Pandas convierte automáticamente un objeto tipo diccionario en un DataFrame.

In [ ]:
restaurantes = pd.DataFrame({
    "Nombre": [ "Sabor Andino", "Pizza House", "La Parrilla", "Sushi World","Taco Feliz", "Burger City", "Café Central", "Mar Azul",
               "Pasta Mia", "El Rancho", "Green Bowl", "Arepa Mix","Wok Express", "Donde Juan", "Food Planet", "La Terraza",
                "Chicken Hot", "Dulce Vida", "El Fogón", "Urban Food" ],
    "Ciudad": ["Bogotá", "Medellín", "Cali", "Bogotá", "Barranquilla", "Cali", "Bogotá", "Cartagena", "Medellín", "Cúcuta",
               "Bogotá", "Bucaramanga", "Cali", "Bogotá", "Medellín", "Pereira", "Bogotá", "Cali", "Tunja", "Bogotá"],
    "Tipo_Comida": ["Colombiana", "Italiana", "Carnes", "Japonesa", "Mexicana", "Rápida", "Café", "Mariscos", "Italiana", "Carnes",
                    "Vegetariana", "Colombiana", "China", "Típica", "Internacional", "Fusión", "Pollo", "Postres","Tradicional", "Rápida"],
    "Calificacion": [4.5, 4.0, 3.8, 4.7, 4.3, 3.9, 4.3, 4.6, 4.1, 3.7, 4.8, 4.2, 4.0, 3.5, 4.0, 4.4, 3.9, 4.9, 3.6, 4.1 ],
    "Numero_Empleados": [ 15, 10, np.nan, 12, 8, 18, None, 14, np.nan, 22, 9, 7, 11, 13, 25, 16, 19, 5, 17, np.nan],
    "Ventas_Mensuales": [ np.nan, 18000000, 32000000, 27000000, 15000000, 35000000, 12000000, np.nan, 21000000, 29000000,17000000,
                         14000000, 23000000, 26000000,40000000, 31000000, 28000000, 9000000, np.nan, 36000000],
    "Años_Funcionamiento": [12, 5, 20, 7, 3, 10, 15, 8, 6, 25, 4, 11, 40, 18, 9, 14, 13, 2, 30, 5],
    "Entrega_Domicilio": [ "Sí", "Sí", "No", "Sí", None, "Sí", "No", "No", "Sí", "No", "Sí", np.nan, "Sí", "No","Sí", "Sí", np.nan, "No",
        "No", "Sí"]
})

restaurantes

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
0,Sabor Andino,Bogotá,Colombiana,4.5,15.0,NaN,12,Sí
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí
2,La Parrilla,Cali,Carnes,3.8,NaN,32000000.0,20,No
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí
4,Taco Feliz,Barranquilla,Mexicana,4.3,8.0,15000000.0,3,None
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí
6,Café Central,Bogotá,Café,4.3,NaN,12000000.0,15,No
7,Mar Azul,Cartagena,Mariscos,4.6,14.0,NaN,8,No
8,Pasta Mia,Medellín,Italiana,4.1,NaN,21000000.0,6,Sí
9,El Rancho,Cúcuta,Carnes,3.7,22.0,29000000.0,25,No
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí
11,Arepa Mix,Bucaramanga,Colombiana,4.2,7.0,14000000.0,11,NaN
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí
16,Chicken Hot,Bogotá,Pollo,3.9,19.0,28000000.0,13,NaN
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No
18,El Fogón,Tunja,Tradicional,3.6,17.0,NaN,30,No
19,Urban Food,Bogotá,Rápida,4.1,NaN,36000000.0,5,Sí

Generar el promedio de alguna variable:

In [ ]:
Calificacion_promedio = restaurantes["Calificacion"].mean()
print(f"la Calificacion promedio es: {Calificacion_promedio}")

la Calificacion promedio es: 4.165

Si la tabla es demasiado grande, y queremos ver algunas filas, usamos:

In [ ]:
restaurantes.head(2) #primeras dos filas

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
0,Sabor Andino,Bogotá,Colombiana,4.5,15.0,NaN,12,Sí
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí

In [ ]:
restaurantes.tail(2) #ultimas 2 filas

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
18,El Fogón,Tunja,Tradicional,3.6,17.0,NaN,30,No
19,Urban Food,Bogotá,Rápida,4.1,NaN,36000000.0,5,Sí

Tipos de datos, resumen de la base o data.frame:

In [ ]:
restaurantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Nombre               20 non-null     object
 1   Ciudad               20 non-null     object
 2   Tipo_Comida          20 non-null     object
 3   Calificacion         20 non-null     float64
 4   Numero_Empleados     16 non-null     float64
 5   Ventas_Mensuales     17 non-null     float64
 6   Años_Funcionamiento  20 non-null     int64
 7   Entrega_Domicilio    17 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 1.4+ KB

Estadísticas descriptivas básicas para variables cuantitativas:

* count = cantidad de datos
* mean = media aritmética
* std = desviación estándar
* min = valor mínimo
* max = valor máximo

In [ ]:
restaurantes.describe()

       Calificacion  Numero_Empleados  Ventas_Mensuales  Años_Funcionamiento
count     20.000000         16.000000      1.700000e+01            20.000000
mean       4.165000         13.812500      2.429412e+07            12.850000
std        0.395068          5.540382      9.122532e+06             9.761768
min        3.500000          5.000000      9.000000e+06             2.000000
25%        3.900000          9.750000      1.700000e+07             5.750000
50%        4.100000         13.500000      2.600000e+07            10.500000
75%        4.425000         17.250000      3.100000e+07            15.750000
max        4.900000         25.000000      4.000000e+07            40.000000

Si queremos conocer la cantidad de filas y columnas:

In [ ]:
restaurantes.shape #(filas, columnas)

(20, 8)

Para seleccionar columnas específicas, usamos una lista que contenga los nombres de las columnas que queremos.

In [ ]:
restaurantes[["Nombre", "Años_Funcionamiento"]]

          Nombre  Años_Funcionamiento
0   Sabor Andino                   12
1    Pizza House                    5
2    La Parrilla                   20
3    Sushi World                    7
4     Taco Feliz                    3
5    Burger City                   10
6   Café Central                   15
7       Mar Azul                    8
8      Pasta Mia                    6
9      El Rancho                   25
10    Green Bowl                    4
11     Arepa Mix                   11
12   Wok Express                   40
13    Donde Juan                   18
14   Food Planet                    9
15    La Terraza                   14
16   Chicken Hot                   13
17    Dulce Vida                    2
18      El Fogón                   30
19    Urban Food                    5

Para filtrar datos y quedarnos solo con aquellos que cumplen las condiciones que especifiquemos:

In [ ]:
restaurantes[(restaurantes["Años_Funcionamiento"] > 10) & (restaurantes["Años_Funcionamiento"] < 28)]

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
0,Sabor Andino,Bogotá,Colombiana,4.5,15.0,NaN,12,Sí
2,La Parrilla,Cali,Carnes,3.8,NaN,32000000.0,20,No
6,Café Central,Bogotá,Café,4.3,NaN,12000000.0,15,No
9,El Rancho,Cúcuta,Carnes,3.7,22.0,29000000.0,25,No
11,Arepa Mix,Bucaramanga,Colombiana,4.2,7.0,14000000.0,11,NaN
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí
16,Chicken Hot,Bogotá,Pollo,3.9,19.0,28000000.0,13,NaN

In [ ]:
restaurantes.isnull() # valores faltantes

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
0,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False
7,False,False,False,False,False,True,False,False
8,False,False,False,False,True,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,True
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,True
17,False,False,False,False,False,False,False,False
18,False,False,False,False,False,True,False,False
19,False,False,False,False,True,False,False,False

In [ ]:
restaurantes.isnull().sum() #suma los valores por columnas, 1 si es faltante 0 si no

Nombre                 0
Ciudad                 0
Tipo_Comida            0
Calificacion           0
Numero_Empleados       4
Ventas_Mensuales       3
Años_Funcionamiento    0
Entrega_Domicilio      3
dtype: int64

In [ ]:
restaurantes1= restaurantes.dropna() #elimina las filas con valores faltantes
restaurantes1

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí
9,El Rancho,Cúcuta,Carnes,3.7,22.0,29000000.0,25,No
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No

In [ ]:
restaurantes1.dropna(subset = ["Ventas_Mensuales"]) # se eliminan las filas que tengan valores faltantes solo en la columna nombrada

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí
9,El Rancho,Cúcuta,Carnes,3.7,22.0,29000000.0,25,No
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No

In [ ]:
restaurantes1["Ventas_Mensuales"] = restaurantes["Ventas_Mensuales"].fillna(restaurantes1["Ventas_Mensuales"].mean())
restaurantes1["Ventas_Mensuales"] = restaurantes["Ventas_Mensuales"].fillna("desconocido")
restaurantes1 # resmplazar valores por nuestro valor sugerido

/tmp/ipykernel_23259/972295408.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurantes1["Ventas_Mensuales"] = restaurantes["Ventas_Mensuales"].fillna(restaurantes1["Ventas_Mensuales"].mean())
/tmp/ipykernel_23259/972295408.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurantes1["Ventas_Mensuales"] = restaurantes["Ventas_Mensuales"].fillna("desconocido")

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí
9,El Rancho,Cúcuta,Carnes,3.7,22.0,29000000.0,25,No
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No

In [ ]:
restaurantes1["Tipo_Comida"] = restaurantes1["Tipo_Comida"].replace("Carnes", "Rápida")
restaurantes1 # remplazar valores por otros

/tmp/ipykernel_23259/2745324989.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurantes1["Tipo_Comida"] = restaurantes1["Tipo_Comida"].replace("Carnes", "Rápida")

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí
9,El Rancho,Cúcuta,Rápida,3.7,22.0,29000000.0,25,No
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No

In [ ]:
restaurantes2 = restaurantes1["Ciudad"].drop_duplicates()
restaurantes2

1     Medellín
3       Bogotá
5         Cali
9       Cúcuta
15     Pereira
Name: Ciudad, dtype: object

In [ ]:
restaurantes1["Ventas_anuales"] = restaurantes1["Ventas_Mensuales"] * 12
#aplicar funcion
restaurantes1["Años_Funcionamiento_ doble"] = restaurantes1["Años_Funcionamiento"].apply(lambda x: x * 2)
restaurantes1

/tmp/ipykernel_23259/763644032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurantes1["Ventas_anuales"] = restaurantes1["Ventas_Mensuales"] * 12
/tmp/ipykernel_23259/763644032.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurantes1["Años_Funcionamiento_ doble"] = restaurantes1["Años_Funcionamiento"].apply(lambda x: x * 2)

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio,Ventas_anuales,Años_Funcionamiento_ doble
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí,216000000.0,10
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí,324000000.0,14
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí,420000000.0,20
9,El Rancho,Cúcuta,Rápida,3.7,22.0,29000000.0,25,No,348000000.0,50
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí,204000000.0,8
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí,276000000.0,80
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No,312000000.0,36
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí,480000000.0,18
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí,372000000.0,28
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No,108000000.0,4

In [ ]:
restaurantes3 = restaurantes1.rename(columns = {"Años_Funcionamiento" : "Antiguedad"})
restaurantes3

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Antiguedad,Entrega_Domicilio,Ventas_anuales,Años_Funcionamiento_ doble
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí,216000000.0,10
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí,324000000.0,14
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí,420000000.0,20
9,El Rancho,Cúcuta,Rápida,3.7,22.0,29000000.0,25,No,348000000.0,50
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí,204000000.0,8
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí,276000000.0,80
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No,312000000.0,36
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí,480000000.0,18
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí,372000000.0,28
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No,108000000.0,4

In [ ]:
restaurantes3["Nombre"] = restaurantes3["Nombre"].str.lower()
restaurantes3["Nombre"] = restaurantes3["Nombre"].str.strip()
restaurantes3["Nombre"] = restaurantes3["Nombre"].str.replace("pizza house", "PIZZA house")
restaurantes3

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Antiguedad,Entrega_Domicilio,Ventas_anuales,Años_Funcionamiento_ doble
1,PIZZA house,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí,216000000.0,10
3,sushi world,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí,324000000.0,14
5,burger city,Cali,Rápida,3.9,18.0,35000000.0,10,Sí,420000000.0,20
9,el rancho,Cúcuta,Rápida,3.7,22.0,29000000.0,25,No,348000000.0,50
10,green bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí,204000000.0,8
12,wok express,Cali,China,4.0,11.0,23000000.0,40,Sí,276000000.0,80
13,donde juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No,312000000.0,36
14,food planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí,480000000.0,18
15,la terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí,372000000.0,28
17,dulce vida,Cali,Postres,4.9,5.0,9000000.0,2,No,108000000.0,4

In [ ]:
grupo = restaurantes3.groupby("Ciudad")["Ventas_Mensuales"].mean()
grupo

Ciudad
Bogotá      23333333.333333
Cali        22333333.333333
Cúcuta           29000000.0
Medellín         29000000.0
Pereira          31000000.0
Name: Ventas_Mensuales, dtype: object

In [ ]:
ordenado = restaurantes3.sort_values(by = "Antiguedad")
ordenado

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Antiguedad,Entrega_Domicilio,Ventas_anuales,Años_Funcionamiento_ doble
17,dulce vida,Cali,Postres,4.9,5.0,9000000.0,2,No,108000000.0,4
10,green bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí,204000000.0,8
1,PIZZA house,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí,216000000.0,10
3,sushi world,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí,324000000.0,14
14,food planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí,480000000.0,18
5,burger city,Cali,Rápida,3.9,18.0,35000000.0,10,Sí,420000000.0,20
15,la terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí,372000000.0,28
13,donde juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No,312000000.0,36
9,el rancho,Cúcuta,Rápida,3.7,22.0,29000000.0,25,No,348000000.0,50
12,wok express,Cali,China,4.0,11.0,23000000.0,40,Sí,276000000.0,80

In [ ]:
valores = restaurantes3.values # cambiar de pandas a un array
valores

array([['PIZZA house', 'Medellín', 'Italiana', 4.0, 10.0, 18000000.0, 5,
        'Sí', 216000000.0, 10],
       ['sushi world', 'Bogotá', 'Japonesa', 4.7, 12.0, 27000000.0, 7,
        'Sí', 324000000.0, 14],
       ['burger city', 'Cali', 'Rápida', 3.9, 18.0, 35000000.0, 10, 'Sí',
        420000000.0, 20],
       ['el rancho', 'Cúcuta', 'Rápida', 3.7, 22.0, 29000000.0, 25, 'No',
        348000000.0, 50],
       ['green bowl', 'Bogotá', 'Vegetariana', 4.8, 9.0, 17000000.0, 4,
        'Sí', 204000000.0, 8],
       ['wok express', 'Cali', 'China', 4.0, 11.0, 23000000.0, 40, 'Sí',
        276000000.0, 80],
       ['donde juan', 'Bogotá', 'Típica', 3.5, 13.0, 26000000.0, 18,
        'No', 312000000.0, 36],
       ['food planet', 'Medellín', 'Internacional', 4.0, 25.0,
        40000000.0, 9, 'Sí', 480000000.0, 18],
       ['la terraza', 'Pereira', 'Fusión', 4.4, 16.0, 31000000.0, 14,
        'Sí', 372000000.0, 28],
       ['dulce vida', 'Cali', 'Postres', 4.9, 5.0, 9000000.0, 2, 'No',
        108000000.0, 4]], dtype=object)

# Uso en Ciencia de Datos: Ventajas y Desventajas de NumPy y Pandas

NumPy y Pandas son la base del ecosistema de Ciencia de Datos y Machine Learning en Python. Sin ellas, implementar algoritmos de optimización, predicción y análisis estadístico sería casi imposible por las limitaciones de rendimiento y memoria de las estructuras nativas de Python (como las listas).

## NumPy (Numerical Python)

**Uso en Ciencia de Datos:**
Es la librería fundamental para cómputo científico y álgebra lineal. En Ciencia de Datos, casi cualquier algoritmo (desde regresión lineal hasta redes neuronales) convierte los datos de entrada en arreglos multidimensionales (matrices o tensores). NumPy ofrece la estructura y funciones matemáticas para realizar operaciones masivas sobre estos tensores (como producto punto, inversión de matrices y cálculo de gradientes) a gran velocidad.

**Ventajas:**
- Velocidad y rendimiento: Sus núcleos internos están escritos en C, ejecutando operaciones a nivel de código compilado y evitando la lentitud del tipado dinámico de Python.
- Vectorización: Permite aplicar operaciones matemáticas a bloques completos de datos sin usar bucles for, optimizando drásticamente el tiempo de ejecución.
- Eficiencia en memoria: Almacena los datos en posiciones contiguas de memoria y exige un solo tipo de dato fijo, reduciendo el consumo de recursos.

**Desventajas:**
- Homogeneidad estricta: Un arreglo de NumPy solo admite un único tipo de dato (ej. solo float64). No mezcla texto con números de forma eficiente.
- Sin etiquetas: Los datos se indexan solo por posición numérica. No tiene nombres de columnas ni filas, lo que dificulta manejar bases de datos tabulares complejas.

## Pandas (Panel Data)

**Uso en Ciencia de Datos:**
Se especializa en manipular, estructurar y hacer Análisis Exploratorio de Datos (EDA). Es clave en el preprocesamiento de proyectos de Ciencia de Datos. Antes de entrenar un algoritmo, los datos crudos suelen tener ruido o imperfecciones; Pandas permite cargar bases de datos, limpiar registros, filtrar filas, agrupar variables y manejar datos faltantes (NaN).

**Ventajas:**
- Flexibilidad (heterogeneidad): Un DataFrame puede tener columnas de texto, números enteros, decimales y booleanos, imitando una base de datos SQL o una hoja de cálculo.
- Etiquetado intuitivo: Accede y filtra datos mediante nombres explícitos de columnas e índices, haciendo el código más legible y con menos errores.
- Herramientas avanzadas: Cuenta con funciones potentes para fusionar tablas (merge), agrupar categorías (groupby) y manejar series temporales o datos nulos.

**Desventajas:**
- Alto consumo de memoria: Pandas crea copias en memoria para muchas transformaciones y arrastra muchos metadatos. No es ideal para Big Data (volúmenes que superan la RAM).
- Menor velocidad en cálculo puro: Para operaciones matemáticas complejas o iteraciones algorítmicas, Pandas es más lento que NumPy por su sobrecarga estructural. Por eso, en Ciencia de Datos se usa Pandas para limpiar los datos y luego se convierten a NumPy con .to_numpy() antes de ingresar al algoritmo.